export const musicData = [
	{
		image: "../assets/handlifted.jpg",
		title: "Music 1",
		artist: "Artist 1",
		url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description: "Description 1",
		year: 2019,
	},
	{
		image: "../assets/handlifted.jpg",
		title: "Music 2",
		artist: "Artist 2",
		url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description: "Description 1",
		year: 2019,
	},
	{
		image: "../assets/handlifted.jpg",
		title: "Music 3",
		artist: "Artist 3",
		url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description: "Description 1",
		year: 2019,
	},
	{
		image: "../assets/handlifted.jpg",
		title: "Music 4",
		artist: "Artist 4",
		url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description: "Description 1",
		year: 2019,
	},
	{
		image: "../assets/handlifted.jpg",
		title: "Music 5",
		artist: "Artist 4",
		url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description: "Description 1",
		year: 2019,
	},
	{
		image: "../assets/handlifted.jpg",
		title: "Music 6",
		artist: "Artist 4",
		url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
		description: "Description 1",
		year: 2019,
	},
];
